name: Retweet Bot
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  retweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: "3.10" }
      - name: Install deps
        run: pip install selenium undetected-chromedriver
      - name: Run bot
        env:
          # Use exactly one of these:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}      # paste JSON from Cookie-Editor
          # COOKIE_HEADER: ${{ secrets.COOKIE_HEADER }}  # or paste Cookie: line from DevTools
        run: python retweet-bot.py
